---
title: "Lophelia GLM"
author: "Zach Proux"
date: "May 29, 2018"
output: html_document
---
```{r}
# Load necessary packages
library(raster)
library(rgdal)
library(sp)
```

```{r}
# Import coral presence/absence data and make it a data.frame
coral = read.csv("../Data/Lophelia.csv")
coral = data.frame(coral)
logic = complete.cases(coral)
coral = cbind(coral, logic)
coral = coral[logic == "TRUE",]
coral = coral[1:3676,]
```

```{r}
library(dplyr)
coral = coral %>% na.omit()
```


```{r}
# Reproject lat_long to WGS 1984 World Mercator to match rasters
lon = coral$LongitudeDD
lat = coral$LatitudeDD
xy = SpatialPoints(cbind(lon, lat), proj4string=CRS("+proj=longlat"))
xy.UTM = spTransform(xy, CRS("+init=epsg:32616"))
UTM.latlon = as.data.frame(xy.UTM)
```

```{r}
# Import raster data 
aspect = raster("../Data/Clip_Aspect1.tif")
slope = raster("../Data/Clip_Slope1.tif")
depth = raster("../Data/Clip_Depth1.tif")
intensity = raster("../Data/Clip_Intensity1.tif")
```

```{r}
# Group files for stacking
files = c("../Data/Clip_Aspect1.tif", "../Data/Clip_Slope1.tif", "../Data/Clip_Depth1.tif", "../Data/Clip_Intensity1.tif")
```

```{r}
# Stack the raster data
RaStack = stack(files, RAT = TRUE)
```

```{r}
# Extract environmental variables for each coordinate
EnVar = extract(RaStack, xy.UTM)
EnVar.df = as.data.frame(EnVar)
# Bind environmental variables to their respective coral presence/absence observations
ModVar = cbind(coral, EnVar.df, UTM.latlon)
# Eliminate observations with no environmental data
work = subset(ModVar, Locality != "North Wall")
write.csv(work, 'work.csv')
```

```{r}
mod3 = glm(Presence ~ Clip_Slope1 + Clip_Aspect1 + Clip_Intensity1,
           data = work, family = "binomial")
summary(mod3)
```

```{r}
plot(mod3)
# Difficult to interpret some of these plots, but there appears to be two distinct portions of the model.  The residuals don't appear to be normally distributed.
# Calculate R-squared
R2logit = function(mod3){
    R2 = 1-(mod3$deviance/mod3$null.deviance)
    return(R2)
    }
R2logit(mod3)
```

```{r}
# Cut data frame to just the variables I want
work.cut = subset(work, select = c(Clip_Aspect1, Clip_Slope1, Clip_Depth1, 
                                   Clip_Intensity1, Presence))
```

```{r}
# Cross-validate
# Split the dataframe into two randomly sorted data frames 
allrows = 1:nrow(work.cut)
trainrows = sample(allrows, replace = F, size = 0.5*length(allrows))
testrows = allrows[-trainrows]
train = work.cut[trainrows,]
test = work.cut[testrows,]
```

```{r}
# Create models from training dataframe
train.mod = glm(Presence ~ Clip_Aspect1 + Clip_Slope1 + Clip_Intensity1,
                data = train, family = "binomial")
summary(train.mod)
R2logit(train.mod)
# R2 = 0.016
# AIC = 370.7 
# Predict response 0-1 based on test data frame
pre.test = predict.glm(train.mod, test, type = "response")
```

```{r}
# Create model from testing dataframe
test.mod = glm(Presence ~ Clip_Aspect1 + Clip_Slope1 + Clip_Intensity1,
                data = test, family = "binomial")
summary(test.mod)
R2logit(test.mod)
# R2 = 0.0119
# AIC = 2359.7
# Predict response 0-1 based on train data frame
pre.train = predict.glm(test.mod, train, type = "response")
```

```{r}
# Compare the predictive values to the observed values graphically
mod.perf = as.data.frame(cbind(test$Presence, pre.train))
ones = mod.perf[mod.perf$V1 == 1,]
zeros = mod.perf[mod.perf$V1 == 0,]
boxplot(mod.perf$pre.train ~ mod.perf$V1, ylab = "Predicted Probability of Cnidarian Occurence", 
        xlab = "Observed Presence or Absence")
t.test(mod.perf$pre.train, mod.perf$V1)
# P = 0.99
# Almost no difference whatsoever between the predicted values for presence observations and absence observations.
```
```{r}
# Produce predictive values for each 10m pixel
mod3.ras = predict(RaStack, mod3)
# Transform logit scale to probabilities
logit2prob = function(mod3.ras){
  odds = exp(mod3.ras)
  prob = odds / (1 + odds)
  return(prob)
}
bc.prob = logit2prob(mod3.ras)
plot(bc.prob, xlab = "Longitude (m)", ylab = "Latitude (m)")
plot(mod3.ras, work.cut$Clip_Intensity1)
# May be easier to plot this prediction raster in ArcMap to get figures.
# Save raster in format that's compatible with ArcGIS to stage maps for presentation
writeRaster(bc.prob, "Loph.Prob", format = "GTiff", overwrite = TRUE)
```

